### ISSUE TITLE
Block diamond is still not correct for rvsdg round trip

### ISSUE THREAD

**Issue by oflatt** [oflatt/eggcc#65] opened 2023-10-11 17:07 UTC
Printing out the value of "x" shows that we are still not doing RVSDG roundtrip correctly, even after #63

**Comment by ezrosent** [comment] 2023-10-16 03:30
I had the chance to debug this a bit this evening. The issue is that we are overwriting `x` when symbolically executing `.D` and then traversing `.B` without resetting `x`.  `.B` is the block we actually visit, and as a result we get a different value when executing the program.

This shouldn't happen: `x` should be an input to each subregion in the corresponding $\gamma$ node we create here, but it isn't being recognized as an input. This is because we are using `live_in` instead of `live_out` to determine the input parameters to the node.

I can send a fix for this in the next day or two.

**Comment by oflatt** [comment] 2023-10-16 18:26
Great job debugging!

**Closed** 2023-10-18 00:06 UTC
